module.exports = {
  getStartedButton: '[data-cy=get-started-button]',
  addTodoButton: '[data-cy=plus-sign]',
  titleInput: '[data-cy=title-input]',
  submitTodo: '[data-cy=add-todo-button]',
  todoCard: '[class=css-1ie3f4j]',
  deleteButton: '[data-cy=delete-button]',
  descriptionInput: '[data-cy=description-space]',
  title: 'Test Title',
  description: 'Test Descr.',
  switches: '[data-cy=switches]',
  lockButton: 'locked',
  completedButton: 'completed',
  toggleButtonFirst: 'Showing pending todos',
  toggleButtonSecond: 'Showing completed todos',
  form: '[class=css-1909024]',
  logoutButton: '[data-cy=logout-button]',
  homeTitle: '[class=css-vfrfzd-Home]',
};
